### ISSUE TITLE
Ubuntu Server 15.10 "ReferenceError: logger is not defined"

### ISSUE THREAD

**Issue by jruels** [thejinx0r/node-gdrive-fuse#90]
It looks like logger may not be defined correctly.  
When running `node client.es6.js` I get the following

```
/node-gdrive-fuse/src/common.es6.js:28
  logger.info( "max cache size was not set. you should exit and manually set it");
  ^

ReferenceError: logger is not defined
    at Object.<anonymous> (/node-gdrive-fuse/src/common.es6.js:28:3)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/node-gdrive-fuse/src/folder.es6.js:8:14)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
```

I could just set the max cache size, but that's just a symptom and not the root cause. 

I'm running nvm with node 5.0, but I've tested with node 4.2.2 as well

```
root@c2d9ab0175c9:/node-gdrive-fuse/src# node --version
v5.0.0
```

Please let me know if I'm missing something, or if I can help by providing more info. 

Thanks,
-js

**Comment by thejinx0r** [comment]
The temporary fix is to set the "maxCache" option in your config file.
I have fixed it, but I haven't merged it in to master yet.

**Comment by jruels** [comment]
Great thanks. I look forward to the patch.

**Comment by scoopydude2002** [comment]
I'm still getting this error on Ubuntu 16.04. Has this patch been merged to master?
